### ISSUE TITLE
Filter model buttons do not work

### ISSUE THREAD

**Issue by jmorel** [SubstraFoundation/substra-frontend#11]
Go to the models section, click on either the "filter" button in the more menu in the list or on the filter button in the detail pane and you'll get no result.

This is because the hash pushed to the searchbar is the traintuples and not the models.

We could fix it easily but then it begs the question of failed traintuples: since these don't have a model, they also don't have a hash we can push to the searchbar.

I see two alternatives:
1. Do not display filter buttons for failed traintuples
2. Add support for filtering on traintuple keys and not just model keys. Then filter failed traintuples on those keys.

**Comment by GuillaumeCisco** [comment]
This issue is almost 1 year old.
Is it still relevant?

**Comment by jmorel** [comment]
This has actually been solved. Filter buttons are now only displayed when relevant and the filter button works as expected.
