### ISSUE TITLE
Refacto + New Features Search Bar

### ISSUE THREAD

**Issue by GuillaumeCisco** [SubstraFoundation/substra-frontend#6]
- [ ] Refacto code for not using material-ui components nor downshift.
- [ ] Add `AND NOT` filter
- [ ] Review First/Second options (maybe put directly challenge:name in the first menu)
- [ ] Use base64 in url and decode it inside backend
- [ ] Fix css on small screens
- [ ] Automagically select right filter when posting uuid directly (May be impossible due to blockchain philosophy)

**Comment by jmorel** [comment]
Since these changes have never been tackled for almost 2 years I think it's safe to say there is no current user demand for them. I'm closing this but of course with new user feedback we could decide to implement some of the features listed here.
