### ISSUE TITLE
[maintenance] Merge substra-ui back into substra-frontend.

### ISSUE THREAD

**Issue by jmorel** [SubstraFoundation/substra-frontend#63]
The substra-ui library was supposed to allow the creation of new frontends for substra but no such project has seen the light and the extra dependance makes substra-frontend harder to maintain. We should really merge substra-ui back into substra-frontend and close substra-ui repository.

Here is the proposed migration plan.

1st step is to migrate all files:
* all components go directly under `src/app/business/common/components`
* globalStyles: lato goes under `assets`, the globalStyle component goes into `src/app/business/common/components`
* icons go under `src/app/business/common/components` in a common folder
* utils/propTypes.js goes `under src/app/utils`
* variables go under assets and are to be merged with existing variables

2nd step is obviously to update all references to these new files instead of substra-ui (and remove all mentions of substra-ui from the codebase).

3rd step is to include in substra-frontend the storybook and jest configurations so that all existing tests are ported to substra-frontend as well.

**Comment by GuillaumeCisco** [comment]
Will `substra-ui` library be shut down?

**Comment by jmorel** [comment]
Yes it will be.
