### ISSUE TITLE
[Bug] Error when clicking on a composite traintuple with status failed

### ISSUE THREAD

**Issue by Esadruhn** [SubstraFoundation/substra-frontend#64]
## Setup

Local deployement of Substra using skaffold
Latest commit on master (tag: 0.0.17)

## Description of the bug

On the models page: http://substra-frontend.node-1.com/model 
I have a composite traintuple with the status 'failed'. When trying to click on it, the page becomes entirely blank.

Opening the dev tools gives me this error: 
```js
react-12ba27.js:2 TypeError: Cannot read property 'hash' of null
```

This happens with two different failed composite traintuples, no problem with failed traintuples and aggregatetuples, nor with 'done' tuple.

The error seems to come from this:
![image](https://user-images.githubusercontent.com/4139100/88787054-93e6de00-d193-11ea-8661-ff108714ec9a.png)

In case of failure, `outHeadModel.outModel` and `outTrunkModel.outModel` are null instead of something like this: `outModel: {hash: "77ac6ae57ef74bc465a676e584c71a4d6f0ae083a5bb29e4a532a38e77355732"}`

**Comment by jmorel** [comment]
This has been fixed in #61 :)
