### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by GuillaumeCisco** [SubstraFoundation/substra-frontend#7]
- [ ] Actions
- [ ] Sagas
- [ ] Reducers
- [ ] Components with Jest
- [ ] Apis
- [ ] Covering

**Comment by jmorel** [comment]
Closing this as adding test for the whole project won't be tackled in a single PR but rather be done little by little. The stack now includes everything we need to tests our codebase and we even have examples for most types of codes, so it should be easier to include tests in the future.
